/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.CardLayout;

/**
 *
 * @author EdgarUrias
 * @author axelm
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        pnlContenido.setLayout(new CardLayout());
        pnlContenido.add(new pnlUsuarios(), "usuarios");
        pnlContenido.add(new pnlAutoridades(), "autoridades");
        pnlContenido.add(new pnlAtenciones(), "atenciones");
        pnlContenido.add(new pnlBaches(), "baches");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        pnlContenido = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        mnuItemUsuarios = new javax.swing.JMenuItem();
        mnuItemAutoridades = new javax.swing.JMenuItem();
        mnuItemBaches = new javax.swing.JMenuItem();
        mnuItemAtencion = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContenido.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        menuOpciones.setText("Opciones");

        mnuItemUsuarios.setText("Usuarios");
        mnuItemUsuarios.addActionListener(this::mnuItemUsuariosActionPerformed);
        menuOpciones.add(mnuItemUsuarios);

        mnuItemAutoridades.setText("Autoridades");
        mnuItemAutoridades.addActionListener(this::mnuItemAutoridadesActionPerformed);
        menuOpciones.add(mnuItemAutoridades);

        mnuItemBaches.setText("Baches");
        mnuItemBaches.addActionListener(this::mnuItemBachesActionPerformed);
        menuOpciones.add(mnuItemBaches);

        mnuItemAtencion.setText("Atencion de baches");
        mnuItemAtencion.addActionListener(this::mnuItemAtencionActionPerformed);
        menuOpciones.add(mnuItemAtencion);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUsuariosActionPerformed
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "usuarios");
    }//GEN-LAST:event_mnuItemUsuariosActionPerformed

    private void mnuItemAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAtencionActionPerformed
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "atenciones");
    }//GEN-LAST:event_mnuItemAtencionActionPerformed

    private void mnuItemAutoridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAutoridadesActionPerformed
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "autoridades");
    }//GEN-LAST:event_mnuItemAutoridadesActionPerformed

    private void mnuItemBachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBachesActionPerformed
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "baches");
    }//GEN-LAST:event_mnuItemBachesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem mnuItemAtencion;
    private javax.swing.JMenuItem mnuItemAutoridades;
    private javax.swing.JMenuItem mnuItemBaches;
    private javax.swing.JMenuItem mnuItemUsuarios;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}