/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author EdgarUrias
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemUsuarios = new javax.swing.JMenuItem();
        mnuItemAutoridades = new javax.swing.JMenuItem();
        mnuItemBaches = new javax.swing.JMenuItem();
        mnuItemAtencion = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblBienvenida.setText("Bienvenido al sistema de baches");

        lblInfo.setText("Haga click en el menú y seleccione una opcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenida)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblInfo)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblBienvenida)
                .addGap(18, 18, 18)
                .addComponent(lblInfo)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        mnuItemUsuarios.setText("Usuarios");
        mnuItemUsuarios.addActionListener(this::mnuItemUsuariosActionPerformed);
        jMenu1.add(mnuItemUsuarios);

        mnuItemAutoridades.setText("Autoridades");
        mnuItemAutoridades.addActionListener(this::mnuItemAutoridadesActionPerformed);
        jMenu1.add(mnuItemAutoridades);

        mnuItemBaches.setText("Baches");
        mnuItemBaches.addActionListener(this::mnuItemBachesActionPerformed);
        jMenu1.add(mnuItemBaches);

        mnuItemAtencion.setText("Atencion de baches");
        mnuItemAtencion.addActionListener(this::mnuItemAtencionActionPerformed);
        jMenu1.add(mnuItemAtencion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemUsuariosActionPerformed

    private void mnuItemAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAtencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemAtencionActionPerformed

    private void mnuItemAutoridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAutoridadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemAutoridadesActionPerformed

    private void mnuItemBachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBachesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemBachesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JMenuItem mnuItemAtencion;
    private javax.swing.JMenuItem mnuItemAutoridades;
    private javax.swing.JMenuItem mnuItemBaches;
    private javax.swing.JMenuItem mnuItemUsuarios;
    // End of variables declaration//GEN-END:variables
}
