/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.AtencionController;
import controllers.AutoridadController;
import controllers.BacheController;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Autoridad;
import models.Bache;

/**
 *
 * @author EdgarUrias
 * @author axelm
 */
public class pnlAtenciones extends javax.swing.JPanel {
    
    private AtencionController atController;
    private Bache bache;
    private BacheController bController;
    private Autoridad autoridad;
    private AutoridadController auController;

    /**
     * Creates new form pnlAtenciones
     */
    public pnlAtenciones() {
        initComponents();
        atController = new AtencionController();
        bController = new BacheController();
        auController = new AutoridadController();
        btnEliminar.setVisible(false);
        cargarAtenciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtenciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblBusqueda = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        cbxEstatus = new javax.swing.JComboBox<>();
        lblBache = new javax.swing.JLabel();
        lblAutoridad = new javax.swing.JLabel();
        btnBuscarBache = new javax.swing.JButton();
        btnBuscarAutoridad = new javax.swing.JButton();
        txtFechaInicio = new com.toedter.calendar.JDateChooser();
        txtFechaSolucion = new com.toedter.calendar.JDateChooser();
        txtBache = new javax.swing.JTextField();
        txtAutoridad = new javax.swing.JTextField();

        tblAtenciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAtenciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAtencionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAtenciones);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Atención de baches");

        lblNombre.setText("Fecha inicio:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lblCorreo.setText("Fecha Solución:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        lblTelefono.setText("Estatus final:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblID.setText("ID:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        txtID.setEditable(false);
        txtID.setColumns(5);

        lblBusqueda.setText("Buscar atenciones por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Autoridad", "Bache" }));

        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En proceso", "Reparado", "Cancelado" }));

        lblBache.setText("Bache:");

        lblAutoridad.setText("Autoridad:");

        btnBuscarBache.setText("Busca bache");
        btnBuscarBache.addActionListener(this::btnBuscarBacheActionPerformed);

        btnBuscarAutoridad.setText("Busca autoridad");
        btnBuscarAutoridad.addActionListener(this::btnBuscarAutoridadActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCorreo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFechaSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblAutoridad)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGuardar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancelar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEliminar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblTelefono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBuscarAutoridad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBache)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBache)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarBache)))
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusqueda)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreo)
                    .addComponent(txtFechaSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBache)
                    .addComponent(btnBuscarBache)
                    .addComponent(txtBache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutoridad)
                    .addComponent(btnBuscarAutoridad)
                    .addComponent(txtAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusqueda)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar_actualizar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarTxts();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        cargarAtenciones();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarBacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBacheActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        dlgBuscarBaches dlg = new dlgBuscarBaches(frame, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        Integer idBache = dlg.getBacheSeleccionado();
        if (idBache != null) {
            this.bache = bController.obtenerBache(idBache);
            txtBache.setText("ID: " + bache.getIdBache());
        }
    }//GEN-LAST:event_btnBuscarBacheActionPerformed

    private void btnBuscarAutoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutoridadActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        dlgBuscarAutoridades dlg = new dlgBuscarAutoridades(frame, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        Integer idAutoridad = dlg.getAutoridadSeleccionada();
        if (idAutoridad != null) {
            autoridad = auController.obtenerAutoridad(idAutoridad);
            txtAutoridad.setText("ID: " + autoridad.getIdAutoridad());
        }
    }//GEN-LAST:event_btnBuscarAutoridadActionPerformed

    private void tblAtencionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAtencionesMouseClicked
        cargarDatos();
    }//GEN-LAST:event_tblAtencionesMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        buscar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void cargarAtenciones(){
        tblAtenciones.setModel(atController.obtenerTablaAtencion());
    }
    
    private void limpiarTxts(){
        txtID.setText("");
        txtBusqueda.setText("");
        txtFechaInicio.setDate(null);
        txtFechaSolucion.setDate(null);
        txtBache.setText("");
        txtAutoridad.setText("");
        btnGuardar.setText("Guardar");
        btnEliminar.setVisible(false);
    }
    
    private void guardar_actualizar(){
        try{
            Date fechaInicio = txtFechaInicio.getDate();
            Date fechaSolucion = txtFechaSolucion.getDate();
            String estatus = cbxEstatus.getSelectedItem().toString().trim();
            if(estatus.isEmpty()){
                JOptionPane.showMessageDialog(this, "El estatus es obligatorio", "Error: Estatus faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(fechaInicio == null){
                JOptionPane.showMessageDialog(this, "La fecha de inicio es obligatoria", "Error: Estatus faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(this.txtBache == null){
                JOptionPane.showMessageDialog(this, "El bache a atender es obligatorio", "Error: Bache faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(this.txtAutoridad == null){
                JOptionPane.showMessageDialog(this, "La autoridad encargada es obligatoria", "Error: Autoridad faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
            java.sql.Date sqlFechaSolucion = null;
            if(fechaSolucion != null){
                sqlFechaSolucion = new java.sql.Date(fechaSolucion.getTime());
                if(sqlFechaInicio.after(sqlFechaSolucion)){
                    JOptionPane.showMessageDialog(this, "La fecha de solución no puede ser antes de la fecha de inicio", "Error: Autoridad faltante", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if(sqlFechaInicio.toString().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "La fecha de inicio es requerida", "Error: Fecha de inicio faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(btnGuardar.getText().equals("Guardar")){
                boolean seAgrego = atController.agregar(sqlFechaInicio, sqlFechaSolucion, estatus, bache.getIdBache(), autoridad.getIdAutoridad());
                if(seAgrego){
                    JOptionPane.showMessageDialog(this, "Atencion agregada correctamente.");
                }else{
                    JOptionPane.showMessageDialog(this, "Error al agregar la atencion", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                int id = Integer.parseInt(txtID.getText().trim());
                boolean seAgrego = atController.actualizarAtencion(id, sqlFechaInicio, sqlFechaSolucion, estatus, bache.getIdBache(), autoridad.getIdAutoridad());
                if(seAgrego){
                    JOptionPane.showMessageDialog(this, "Atencion actualizada correctamente.");
                }else{
                    JOptionPane.showMessageDialog(this, "Error al actualizar la atencion", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            cargarAtenciones();
            limpiarTxts();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void eliminar(){
        try{
            int id = Integer.parseInt(txtID.getText().trim());
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar la atencion?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if(confirmacion == JOptionPane.YES_OPTION){
                boolean seElimino = atController.eliminarAtencion(id);
                if(seElimino){
                    JOptionPane.showMessageDialog(this, "Se elimino correctamente la atencion");
                    limpiarTxts();
                }else{
                    JOptionPane.showMessageDialog(this, "Error al eliminar la atencion", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Operación cancelada");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarDatos(){
        int fila = tblAtenciones.getSelectedRow();
        if(fila >= 0){
            txtID.setText(tblAtenciones.getValueAt(fila, 0).toString());
            bache = bController.obtenerBache((int) tblAtenciones.getValueAt(fila, 1));
            txtBache.setText("ID: " + bache.getIdBache());
            autoridad = auController.obtenerAutoridad((int) tblAtenciones.getValueAt(fila, 2));
            txtAutoridad.setText("ID: " + autoridad.getIdAutoridad());
            String fechaInicioStr = tblAtenciones.getValueAt(fila, 3).toString();
            Date fechaInicio = java.sql.Date.valueOf(fechaInicioStr);
            txtFechaInicio.setDate(fechaInicio);
            Object fchSolucion = tblAtenciones.getValueAt(fila, 4);
            if(fchSolucion != null){
                String fechaSolucionStr = fchSolucion.toString();
                Date fechaSolucion = java.sql.Date.valueOf(fechaSolucionStr);
                txtFechaSolucion.setDate(fechaSolucion);
            }
            String opcion = tblAtenciones.getValueAt(fila, 5).toString();
            int index;
            switch (opcion) {
                case "pendiente":
                    index = 0;
                    break;
                case "en proceso":
                    index = 1;
                    break;
                case "reparado":
                    index = 2;
                    break;
                case "cancelado":
                    index = 3;
                    break;
                default:
                    index = 4;
            }
            cbxEstatus.setSelectedIndex(index);
            btnGuardar.setText("Actualizar");
            btnEliminar.setVisible(true);
        }
    }
    
    private void buscar(){
        try{
            String filtro = cbxEstatus.getSelectedItem().toString().trim();
            String busqueda = txtBusqueda.getText().trim();
            if(filtro.equals("Seleccione")){
                cargarAtenciones();
            }else if(filtro.equals("Bache")){
                if(busqueda.isEmpty()){
                    cargarAtenciones();
                }else{
                    int idBache = Integer.parseInt(busqueda);
                    tblAtenciones.setModel(atController.obtenerTablaAtencionPorBache(idBache));
                }
            }else{
                if(busqueda.isEmpty()){
                    cargarAtenciones();
                }else{
                    int idAutoridad = Integer.parseInt(busqueda);
                    tblAtenciones.setModel(atController.obtenerTablaAtencionPorAutoridad(idAutoridad));
                }
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "La busqueda debe ser un numero entero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAutoridad;
    private javax.swing.JButton btnBuscarBache;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxEstatus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutoridad;
    private javax.swing.JLabel lblBache;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tblAtenciones;
    private javax.swing.JTextField txtAutoridad;
    private javax.swing.JTextField txtBache;
    private javax.swing.JTextField txtBusqueda;
    private com.toedter.calendar.JDateChooser txtFechaInicio;
    private com.toedter.calendar.JDateChooser txtFechaSolucion;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
