/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.AutoridadController;
import javax.swing.JOptionPane;

/**
 *
 * @author EdgarUrias
 */
public class pnlAutoridades extends javax.swing.JPanel {

    private AutoridadController aController;
    /**
     * Creates new form pnlAutoridades
     */
    public pnlAutoridades() {
        aController = new AutoridadController();
        initComponents();
        btnEliminar.setVisible(false);
        cargarAutoridades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblDependencia = new javax.swing.JLabel();
        txtDependencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAutoridades = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        lblBusqueda = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 300));

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInfo.setText("Administración de autoridades");

        lblTelefono.setText("Telefonos:");

        txtID.setEditable(false);
        txtID.setColumns(5);

        txtNombre.setColumns(20);

        txtCorreo.setColumns(15);

        txtTelefono.setColumns(15);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblNombre.setText("Nombre:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lblCorreo.setText("Correo electronico:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        lblID.setText("ID:");

        lblDependencia.setText("Dependencia:");

        txtDependencia.setColumns(15);

        tblAutoridades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAutoridades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAutoridadesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAutoridades);

        jScrollPane1.setViewportView(jScrollPane2);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        lblBusqueda.setText("Busqueda por ID de autoridad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDependencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBusqueda))
                        .addContainerGap(88, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDependencia)
                            .addComponent(txtDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarActualizar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarTxts();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        cargarAutoridades();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblAutoridadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAutoridadesMouseClicked
        cargarDatos();
    }//GEN-LAST:event_tblAutoridadesMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        buscar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void cargarAutoridades(){
        tblAutoridades.setModel(aController.obtenerTablaAutoridades());
    }
    
    private void limpiarTxts(){
        txtID.setText("");
        txtBusqueda.setText("");
        txtCorreo.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDependencia.setText("");
        btnGuardar.setText("Guardar");
        btnEliminar.setVisible(false);
    }
    
    private void guardarActualizar(){
        try{
            String nombre = txtNombre.getText().trim();
            String correo = txtCorreo.getText().trim();
            String telefono = txtTelefono.getText().trim();
            String dependencia = txtDependencia.getText().trim();
            if(nombre.isEmpty()){
                JOptionPane.showMessageDialog(this, "Todos los campos son necesarios, favor de introducir el nombre", "Error: Nombre faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(correo.isEmpty()){
                JOptionPane.showMessageDialog(this, "Todos los campos son necesarios, favor de introducir el correo", "Error: Correo faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(telefono.isEmpty()){
                JOptionPane.showMessageDialog(this, "Todos los campos son necesarios, favor de introducir el telefono", "Error: Telefono faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(dependencia.isEmpty()){
                JOptionPane.showMessageDialog(this, "Todos los campos son necesarios, favor de introducir la dependencia", "Error: Dependencia faltante", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(btnGuardar.getText().equals("Guardar")){
                boolean seAgrego = aController.agregar(nombre, correo, telefono, dependencia);
                if(seAgrego){
                    JOptionPane.showMessageDialog(this, "Autoridad agregada correctamente.");
                }else{
                    JOptionPane.showMessageDialog(this, "Error al agregar a la autoridad", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                int id = Integer.parseInt(txtID.getText().trim());
                boolean seAgrego = aController.actualizarAutoridad(id, nombre, correo, telefono, dependencia);
                if(seAgrego){
                    JOptionPane.showMessageDialog(this, "Autoridad actualizada correctamente.");
                }else{
                    JOptionPane.showMessageDialog(this, "Error al actualizar a la autoridad", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            cargarAutoridades();
            limpiarTxts();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void eliminar(){
        try{
            int id = Integer.parseInt(txtID.getText().trim());
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar a la autoridad?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if(confirmacion == JOptionPane.YES_OPTION){
                boolean seElimino = aController.eliminarAutoridad(id);
                if(seElimino){
                    JOptionPane.showMessageDialog(this, "Se elimino correctamente la autoridad");
                    limpiarTxts();
                    cargarAutoridades();
                }else{
                    JOptionPane.showMessageDialog(this, "Error al eliminar la autoridad", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Operación cancelada");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarDatos(){
        int fila = tblAutoridades.getSelectedRow();
        if(fila >= 0){
            txtID.setText(tblAutoridades.getValueAt(fila, 0).toString());
            txtNombre.setText(tblAutoridades.getValueAt(fila, 1).toString());
            txtCorreo.setText(tblAutoridades.getValueAt(fila, 2).toString());
            txtTelefono.setText(tblAutoridades.getValueAt(fila, 3).toString());
            txtDependencia.setText(tblAutoridades.getValueAt(fila, 4).toString());
            btnGuardar.setText("Actualizar");
            btnEliminar.setVisible(true);
        }
    }
    
    private void buscar(){
        String filtro = txtBusqueda.getText().trim();
        if(filtro.isEmpty()){
            cargarAutoridades();
        }else{
            tblAutoridades.setModel(aController.obtenerTablaAutoridadesPorFiltro(filtro));
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDependencia;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tblAutoridades;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDependencia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
